apiVersion: apps/v1
kind: Deployment
metadata:
  name: julian-deployment
  labels:
    app: julian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: julian
  template:
    metadata:
      labels:
        app: julian
    spec:
      containers:
        - name: julian
          image: julianrc1/julian-service:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: julian-service
spec:
  selector:
    app: julian
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
