apiVersion: apps/v1
kind: Deployment
metadata:
  name: duque-deployment
  labels:
    app: duque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duque
  template:
    metadata:
      labels:
        app: duque
    spec:
      containers:
        - name: duque
          image: sduquec/duque-deployment:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: duque-service
spec:
  selector:
    app: duque
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP