FROM gcc:latest
RUN apt-get update && apt-get install -y git libasio-dev
RUN git clone https://github.com/CrowCpp/Crow.git /crow
WORKDIR /app
COPY . .
RUN g++ -I /crow/include -o john john.cpp
CMD ["./john"]